### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by yurgon** [tuvistavie/elixir-web-push-encryption#16]
Hi 
I always got "sender is not authenticated"
What key I need to use for gcm_api_key ? 
Just generated from "mix web_push.gen.keypair" ?

**Comment by danhper** [comment]
I am not really sure how authentication is currently handled by GCM or FCM.
I think this might be related to https://github.com/danhper/elixir-web-push-encryption/issues/14 so maybe try with and without sending an auth key.

**Comment by yurgon** [comment]
Thanks, it helps
