### ISSUE TITLE
Sending web push fails on OTP 26

### ISSUE THREAD

**Issue by harrygr** [tuvistavie/elixir-web-push-encryption#31]
I noticed sending of push notifications were failing after I updated to Elixir 1.15.0 on OTP 26. My app is using HTTPoison for the HTTP client.

This is the error that was resulting:

```
{:error, %HTTPoison.Error{reason: {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}, id: nil}}
```

I noticed that on OTP 25 I was getting this warning, even though web push was working:

```
[warning] Description: ~c"Server authenticity is not verified since certificate path validation is not enabled"
     Reason: ~c"The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."
```

I suspect that a change in OTP 26 has meant that requests that cannot verify server authenticity now fail instead of just issuing a warning. I don't think it's Elixir 1.15 related as compiling my app on 1.15 with OTP 25 works fine.

I also came accross this thread that talks about that warning: https://elixirforum.com/t/warning-description-authenticity-is-not-established-by-certificate-path-validation/41588/4

It mentions to not override the SSL defaults as it clobbers the rest of the default configuration.

I feel this line could be responsible: https://github.com/danhper/elixir-web-push-encryption/blob/master/lib/web_push_encryption/push.ex#L66

Is there a reason it needs to specify the SSL version? I feel that removing it would fix the problem in OTP 26 but I currently don't have an easy way to test it as OTP 26 is not yet easily available for my system (MacOS).

**Comment by danhper** [comment]
Hi, very sorry for the delay.
I think that at the time I wrote this code, the default version was 1.1 and GCM wanted 1.2 or something like that.
It would be good if this could be tested before making changes though. Is there any chance you could try changing the version to 1.3 (even if it's in OTP 25, doesn't matter) and see if it works please?

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/web-push-elixir

Hi, I've created a library that supports OTP 26 that is heavily inspired by your work @danhper thank you 🙏
Feel free to check it out and raise any issues you come across over there 😄
