### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by splagemann** [tuvistavie/elixir-web-push-encryption#7]
Hi,
thanks for this library. I'm getting an ArgumentError since the last release.

```
(web_push_encryption) lib/web_push_encryption/push.ex:53: WebPushEncryption.Push.make_request_params/3
2018-04-09T09:00:08.511140+00:00 app[worker.1]:     (web_push_encryption) lib/web_push_encryption/push.ex:44: WebPushEncryption.Push.send_web_push/3
```

As far as I can see, PR #6 changed `headers` from a list to a map. That's why this is failing https://github.com/tuvistavie/elixir-web-push-encryption/blob/master/lib/web_push_encryption/push.ex#L53. I'm not too experienced with Elixir, is there something wrong on my end or is it an error in the last change?

Happy to provide a PR when confirmed.

**Comment by danhper** [comment]
Hi @splagemann, thank you for reporting this.
Indeed, I did not check the last PR carefully enough.
Would you be kind enough to send a PR with a fix?
Thank you very much.

**Comment by splagemann** [comment]
Thanks for merging. Can you also bump the version? Then this can be closed! Thanks

**Comment by danhper** [comment]
Yes, I was just adding a test to make sure this does not happen again, just a second :smiley:

**Comment by danhper** [comment]
I just bumped the version, thanks again for your help!!
